# Use the official Node.js image as a base. Use the alpine version to keep the image size small.
FROM node:22-alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json
COPY package.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose the port the app runs on (e.g., 8080)
EXPOSE 8080

# Define the command to run the application
CMD ["npm", "run", "start:prod"]
