version: '3.8'
name: node-microservices

services:
  service1:
    image: node-postgres-starter-kit
    container_name: service1
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - '8081:8080'
    networks:
      - local
    command: npm start
  service2:
    image: node-postgres-starter-kit
    container_name: service2
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - '8082:8080'
    networks:
      - local
    command: npm start
  service3:
    image: node-postgres-starter-kit
    container_name: service3
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - '8083:8080'
    networks:
      - local
    command: npm start
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '8080:80'
    networks:
      - local
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - service1
      - service2
      - service3

networks:
  local:
    driver: bridge
